// Generated by apps/word-taskpane/src/build.ts. Do not edit; edit PROBED_REQUIREMENT_SETS.
export const PROBE_REPORT_VERSION = 1;
export const PROBED_REQUIREMENT_SETS = [
  { name: "WordApi", version: "1.1" },
  { name: "WordApi", version: "1.2" },
  { name: "WordApi", version: "1.3" },
  { name: "WordApi", version: "1.4" },
  { name: "WordApi", version: "1.5" },
  { name: "WordApi", version: "1.6" },
  { name: "WordApi", version: "1.7" },
  { name: "WordApi", version: "1.8" },
  { name: "WordApi", version: "1.9" },
  { name: "CustomXmlParts", version: "1.1" },
];
